language: java

jdk:
  - openjdk8

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

install: mvn -B install -U -DskipTests=true

script: mvn -B verify -U -Dmaven.javadoc.skip=true

after_success:
  - ./cd/deploy.sh

cache:
  directories:
  - $HOME/.m2

env:
  global:

branches:
  only:
    - master
    - /^release.*$/